# https://github.com/psf/black/blob/master/README.md#how-black-wraps-lines
[tool.isort]
force_grid_wrap = 0
include_trailing_comma = true
known_first_party = [
]
known_third_party = [
    "PIL",
    "Xlib",
    "aiortc",
    "av",
    "numpy",
]
line_length = 120
multi_line_output = 3
use_parentheses = true

[tool.black]
line-length = 120
target-version = ["py37"]
