# https://github.com/psf/black/blob/master/README.md#how-black-wraps-lines
[tool.isort]
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
known_first_party = [
    "x2webrtc",
]
known_third_party = [
    "PIL",
    "Xlib",
    "aiortc",
    "av",
    "numpy",
]
line_length = 120

[tool.black]
line-length = 120
target-version = ["py36"]
